### ISSUE TITLE
I am getting this error in production

### ISSUE THREAD

**Issue by dunake** [itskingori/pesapal-gem#26]
Greetings @itskingori ,  I seem to be having an issue with the gem implementation. On my development environment, everything seems to be working fine, however, in production, I get this error, on the iframe

Problem: consumer_key_unknown | Advice: > |

and yes the API keys are set on an environment variable so I am using different API keys for development and production

**Comment by itskingori** [comment]
@dunake A few questions:

1. Just to make sure we're on the same page? What version?
2. The `consumer_key_unknown` error seems like Pesapal doesn't know your key. Could you double check that the key is set correctly.
3. Assuming you're on the latest version, could you make sure on production you initialize the variable like this:
    ```ruby
    # Sets environment to :production
    pesapal = Pesapal::Merchant.new(:production)
    ```

Guessing really. Difficult to help/debug without any code.

**Comment by itskingori** [comment]
@dunake This doesn't seem to be a problem with the gem. See:

1. http://developer.pesapal.com/forum/2-pesapal-integration/106-problem-consumerkeyunknown--advice-g-
2. http://developer.pesapal.com/forum/2-pesapal-integration/2134-problem-consumerkeyunknown--advice-g-

I'd suggest you check the forums first.

**Comment by itskingori** [comment]
@dunake Closing due to no response. Re-open if it's still an issue.
